### ISSUE TITLE
Publish to pub.dev

### ISSUE THREAD

**Issue by jaripekkala** [davidmartos96/sqflite_sqlcipher#12]
First of all, thank you @davidmartos96 for the package and keeping it up to date! 💯 

This looks pretty much exactly what we would want to use in our app. However, there is a small blocker for us; the package is not published.

We really can't add a package dependency to a git repository that one day might not be available anymore. Publishing the package to pub.dev gives huge advantage as we can be assured that the version will be available even after years.

Is there a plan to publish the package to pub.dev?

**Comment by davidmartos96** [comment]
Thank you @jaripekkala . I will have to think about it, because publishing  also implies some level of compromise. My teammate and I created this repository to use in our own project and we made it public so that it is available for everyone.
If you worry about the repo not being available in the future, you could pretty much fork this repo and stick with a version that works for your own project.
If we do publish it, we don't really know how to make the versioning, since the changes usually are being merged from base sqflite, but probably the package itself needs its own versioning.
Do you have any thoughts about it?

**Comment by jaripekkala** [comment]
> If you worry about the repo not being available in the future, you could pretty much fork this repo and stick with a version that works for your own project.

You are right, though not ideal for us.

> If we do publish it, we don't really know how to make the versioning, since the changes usually are being merged from base sqflite, but probably the package itself needs its own versioning.

Agree, would expect this package to have its own versioning. I wouldn't personally even try to match the versions.

**Comment by jaripekkala** [comment]
Just for example what I meant

sqflite_sqlcipher|sqflite|changes
---|---|---
v1.0.0|v1.2.2|
v1.0.1 |v1.2.3|sqflite bug fix
v1.0.2|v1.2.4|sqflite bug fix
v1.1.0|v1.3.0|sqflite feature
v1.1.1|v1.3.0|sqflite_sqlcipher bug fix

**Comment by idootop** [comment]
> 
> 
> Thank you @jaripekkala . I will have to think about it, because publishing also implies some level of compromise. My teammate and I created this repository to use in our own project and we made it public so that it is available for everyone.
> If you worry about the repo not being available in the future, you could pretty much fork this repo and stick with a version that works for your own project.
> If we do publish it, we don't really know how to make the versioning, since the changes usually are being merged from base sqflite, but probably the package itself needs its own versioning.
> Do you have any thoughts about it?

This package is so great. Thanks :)

**Comment by MobiliteDev** [comment]
Hi,

First of all, thank you for your package, it's great ! 👍

We need the same as @jaripekkala , a package want to use your package for having encryption, but it can't be published because of 'dependency_overrides' method.

You will have this message when you want to publish: 

>  Your pubspec.yaml must not override non-dev dependencies. 

As mentionned in this [issue](https://github.com/hhtokpinar/sqfEntity/issues/13), can you think it's possible to publish it on pub dev please ?

**Comment by davidmartos96** [comment]
@MobiliteDev I reached out to alextekartik, the creator of `sqflite` https://github.com/tekartik/sqflite/pull/396#issuecomment-597377720, because to publish it I think it would be better to recreate the plugin without completely duplicating the `sqflite` Dart code, because `sqlflite_sqlcipher` only modifies the native implementation. Instead, use sqflite as a dependency in the `sqflite_sqlcipher` pubspec and import the Dart code needed.
I have created a branch `publish` that does that, and in which a dependency override is not needed. Only a git dependency for the time being. I haven't tested it on iOS, since I don't own one myself but you could try that branch and let me know how it goes.
```
dependencies:
  sqflite_sqlcipher: 
    git:
      url: https://github.com/davidmartos96/sqflite_sqlcipher
      path: sqflite
      ref: publish
```
The current downside at the moment would be that both `sqflite`and `sqflite_sqlicipher` native implementations would be bundled in the final APK because at the moment there is not a package `sqflite_common` or similar.
Would be great to hear if the dependency above works in you projects. It works on mine, but maybe I missed some step in the refactor.

**Comment by davidmartos96** [comment]
I've finally made the plugin as a pub package https://pub.dev/packages/sqflite_sqlcipher 
The reference for the plugin is in the branch `publish`. I will wait a bit until merging it into master because it will conflict with the previous install instructions.
I will close it. Let me know if you find any issues.

**Comment by MobiliteDev** [comment]
Hi, thank you, it's a big news !
I will made a test this week with your example project on an iOS device and tell you if all is fine.

Regards

**Comment by jaripekkala** [comment]
> I haven't tested it on iOS, since I don't own one myself but you could try that branch and let me know how it goes.

We can confirm that the latest `sqflite_sqlcipher` version from pub.dev is working great on both Android and iOS.

Thank you!

**Comment by Thetyne** [comment]
i just add turn off cipher_memory_security pragma for my databases on Android, because SQLCipher library is very slow for large query insert datas on many devices.

PRAGMA cipher_memory_security = OFF

this plugin work great on Android and iOS. Can you add macos support ?

**Comment by davidmartos96** [comment]
@Thetyne Yes, I have also turned off that pragma on my own app. I do it in the `onConfigure` callback.

About the macos implementation, try with version `1.0.0+6`. I forgot to include macos in the original package version. If it doesn't work, please file a different issue and I will take a look :wink:
