### ISSUE TITLE
Is there a simple way to use this package outside of Flutter?

### ISSUE THREAD

**Issue by lollita** [davidmartos96/sqflite_sqlcipher#16]
[see](https://github.com/tekartik/sqflite/issues/412)

**Comment by davidmartos96** [comment]
Since this package is based on sqflite_common and it delegates the SqlCipher implementation to native libraries on iOS and Android I don't think there is an easy way to do it. 
Your best bet if you want to use SqlCipher on desktop at the moment would be to take a look at `moor_ffi` and override the Sqlite dynamic library with your own compiled version of SqlCipher.

**Comment by davidmartos96** [comment]
@lollita This package relies on Platform channels which is specific to Flutter. Same happens in the sqflite package.
To use SqlCipher on a pure Dart process I think FFI is the only option, but not the purpose of this package.
