### ISSUE TITLE
warning: [deprecation] PluginRegistry in io.flutter.plugin.common has been deprecated import io.flutter.plugin.common.PluginRegistry.Registrar;

### ISSUE THREAD

**Issue by JAICHANGPARK** [davidmartos96/sqflite_sqlcipher#24]
Now I had some build warning about this plugin

```
sqflite_sqlcipher-1.1.1\android\src\main\java\com\davidmartos96\sqflite_sqlcipher\SqfliteSqlCipherPlugin.java:36:
```

**Comment by davidmartos96** [comment]
What version of Flutter are you using? I don't get that warning when using `flutter run` or `flutter build apk`.

**Comment by JAICHANGPARK** [comment]
@davidmartos96 Thank you for replied my issue

Now I'm using flutter beta channel 

```
Flutter (Channel beta, 1.23.0-18.1.pre, on Microsoft Windows [Version 10.0.19041.572],
```

**Comment by davidmartos96** [comment]
Thanks! I was able to get the warning in beta.
The warning is because the plugin is backcompatible with the android embedding v1. So until it is removed, that deprecated code should still be there for people who have not migrated to v2 yet.

Quote from https://flutter.dev/docs/development/packages-and-plugins/plugin-api-migration

"Also, note that the plugin should still contain the static registerWith() method to remain compatible with apps that don’t use the v2 Android embedding. (See Upgrading pre 1.12 Android projects for details.) The easiest thing to do (if possible) is move the logic from registerWith() into a private method that both registerWith() and onAttachedToEngine() can call. Either registerWith() or onAttachToEngine() will be called, not both."

I'll close the issue. Thanks for letting me know that it started to warn in Flutter 1.23 !!

**Comment by JAICHANGPARK** [comment]
@davidmartos96 Nice 
And Thanks for your works 👍
