### ISSUE TITLE
Unused libs in release apk

### ISSUE THREAD

**Issue by lokeez** [davidmartos96/sqflite_sqlcipher#25]
Hello!
First, thanks for this package!

When I compiling release package of my app, flutter generates libs for unused platforms. Is this `sqflite_sqlcipher` bug or `flutter`?

Compile command:
`flutter build apk --target-platform android-arm,android-arm64 --no-tree-shake-icons`

![Screenshot](http://i.piccy.info/i9/b9d0fd7ccba6d46c275a57fe2461ac31/1604300658/122789/1403434/71377Skrynshot_2020_11_02_08_53_00.png)

```
flutter doctor -v
[√] Flutter (Channel stable, 1.22.3, on Microsoft Windows [Version 10.0.18362.295], locale ru-UA)
    • Flutter version 1.22.3 at C:\flutter
    • Framework revision 8874f21e79 (3 days ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\Oleg\AppData\Local\Android\sdk
    • Platform android-29, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] Connected device
    ! No devices available
```

Can you help to reduce apk size? :)

**Comment by davidmartos96** [comment]
Hello! I'm not really sure if that's a bug in Flutter when using native plugins or if something can be changed in the plugin.
On my project, this is what I do to build the desired architectures.
In your app/build.gradle file:
```
buildTypes {
    release {
        ndk {
            abiFilters 'armeabi-v7a', 'arm64-v8a'
        }
    }
}
```

Watch out releasing the apk you got there, because ameabi-v7 devices wouldn't even open because the libflutter.so file is missing.

Another thing I do as well is to generate an appbundle instead of an apk

`flutter build appbundle --target-platform android-arm,android-arm64`

**Comment by lokeez** [comment]
That works! Thank you!
