### ISSUE TITLE
Could you extend the support for Desktop,Linux and web ?

### ISSUE THREAD

**Issue by raghavan-mookiah** [davidmartos96/sqflite_sqlcipher#35]
Currently the plugin support only ANDROID IOS  and  MACOS. Do you have a roadmap to support desktop, Linux and web?

**Comment by davidmartos96** [comment]
@raghavan-mookiah Hello! I don't have plans to include support for Linux and Windows in this package because those platforms don't provide the Sqlcipher native libraries unless thay are installed by the end user.
You can still use Sqlcipher in those platforms though, but not through this package which relies in platform channels. Check out the following comment: https://github.com/davidmartos96/sqflite_sqlcipher/issues/28#issuecomment-733636725

About web, I don't think is possible with Sqlcipher.
